f=open("C:/code/playground/jump to python/03장 프로그램의 입력과 출력/03-4 연습문제/Q7.txt","w")
f.write("Life is too short \nyou need java")
f.close()
f=open("C:/code/playground/jump to python/03장 프로그램의 입력과 출력/03-4 연습문제/Q7.txt","r")
read=f.read()
read=read.replace("java","python")
f.close()
f=open("C:/code/playground/jump to python/03장 프로그램의 입력과 출력/03-4 연습문제/Q7.txt","w")
f.write(read)
f.close()