f=open("C:/code/playground/jump to python/07장 종합문제/abc.txt","r")
text=f.read()
f.close()
text=text.split("\n")
text.reverse()
f=open("C:/code/playground/jump to python/07장 종합문제/abc.txt","w")
for i in  text:
    f.write(i)
    f.write("\n")
f.close()
